#!/usr/bin/env node
// Run: node scripts/generate-seed.js > supabase/seed.sql
// Requires: npm install (bcryptjs must be installed)

const bcrypt = require("bcryptjs");

async function main() {
  const ROUNDS = 10;

  const operators = [
    { name: "James Nguyen",      section: "Rubber Lab",    pin: "1234" },
    { name: "Sarah Mitchell",    section: "Rubber Lab",    pin: "5678" },
    { name: "Carlos Rodriguez",  section: "Vulcanization", pin: "2468" },
    { name: "Anna Kowalski",     section: "Vulcanization", pin: "1357" },
    { name: "David Okafor",      section: "Assembly",      pin: "9012" },
    { name: "Emma Thompson",     section: "Assembly",      pin: "3456" },
    { name: "Michael Chen",      section: "Testing & QC",  pin: "7890" },
    { name: "Priya Sharma",      section: "Testing & QC",  pin: "2580" },
    { name: "Robert Hansen",     section: "Shipping",      pin: "1470" },
    { name: "Leila Ahmadi",      section: "Shipping",      pin: "3690" },
  ];

  const hashes = {};
  for (const op of operators) {
    hashes[op.name] = await bcrypt.hash(op.pin, ROUNDS);
  }

  console.log(`-- Seed data for Manufacturing Operations Platform`);
  console.log(`-- Generated by scripts/generate-seed.js`);
  console.log(`-- Operator PINs (for testing):`);
  for (const op of operators) {
    console.log(`--   ${op.name}: ${op.pin}`);
  }
  console.log();

  console.log(`-- Sections`);
  console.log(`INSERT INTO sections (name, color) VALUES`);
  console.log(`  ('Rubber Lab',    '#6366f1'),`);
  console.log(`  ('Vulcanization', '#f59e0b'),`);
  console.log(`  ('Assembly',      '#10b981'),`);
  console.log(`  ('Testing & QC',  '#ef4444'),`);
  console.log(`  ('Shipping',      '#3b82f6');`);
  console.log();

  console.log(`-- Operators (PIN hashes generated at run time)`);
  console.log(`INSERT INTO operators (name, section_id, pin, is_active) VALUES`);
  const opRows = operators.map((op, i) => {
    const hash = hashes[op.name];
    const comma = i < operators.length - 1 ? "," : ";";
    return `  ('${op.name}', (SELECT id FROM sections WHERE name = '${op.section}'), '${hash}', true)${comma}`;
  });
  opRows.forEach((r) => console.log(r));
  console.log();

  console.log(`-- Work Orders`);
  console.log(`INSERT INTO work_orders (job_number, product_name, product_type, quantity_required, status) VALUES`);
  console.log(`  ('WO-2026-0021', 'HP Straddle Packer 5.5"',            'Oil & Gas',     2, 'open'),`);
  console.log(`  ('WO-2026-0022', 'Single Element Packer 4.5"',          'Oil & Gas',     4, 'open'),`);
  console.log(`  ('WO-2026-0023', 'Geotechnical Test Packer 3"',         'Geotechnical',  1, 'open'),`);
  console.log(`  ('WO-2026-0024', 'Casing Shoe Packer 7"',               'Oil & Gas',     3, 'open'),`);
  console.log(`  ('WO-2026-0025', 'Mining Borehole Packer 4"',           'Mining',        6, 'open'),`);
  console.log(`  ('WO-2026-0026', 'Dual Packer System 5"',               'Oil & Gas',     2, 'open'),`);
  console.log(`  ('WO-2026-0027', 'Water Well Isolation Packer 3.5"',    'Geotechnical',  1, 'open'),`);
  console.log(`  ('WO-2026-0028', 'Inflatable Bridge Plug 6"',           'Oil & Gas',     1, 'in_progress'),`);
  console.log(`  ('WO-2026-0029', 'Compaction Grouting Packer 2.5"',     'Mining',        5, 'open'),`);
  console.log(`  ('WO-2026-0030', 'Swellable Packer 4.5"',               'Oil & Gas',     4, 'open');`);
  console.log();

  console.log(`-- Tasks`);
  console.log(`INSERT INTO tasks (section_id, title, frequency, order_index) VALUES`);
  const tasks = [
    // Rubber Lab
    ["Rubber Lab", "Inspect rubber compound batch",               "daily",   1],
    ["Rubber Lab", "Calibrate mixing equipment temperature",       "daily",   2],
    ["Rubber Lab", "Clean rubber mixing machinery",                "daily",   3],
    ["Rubber Lab", "Document compound lot number on work order",   "per_job", 4],
    ["Rubber Lab", "Verify cure time against batch specification", "per_job", 5],
    // Vulcanization
    ["Vulcanization", "Calibrate vulcanization press temperature", "daily",   1],
    ["Vulcanization", "Check autoclave pressure gauge",            "daily",   2],
    ["Vulcanization", "Inspect mould surfaces for contamination",  "per_job", 3],
    ["Vulcanization", "Set press cycle timer to job specification","per_job", 4],
    ["Vulcanization", "Record cure temperature and pressure",      "per_job", 5],
    // Assembly
    ["Assembly", "Check safety equipment at workstation",          "daily",   1],
    ["Assembly", "Verify packer element dimensions to drawing",    "per_job", 2],
    ["Assembly", "Inspect mandrel surface for corrosion",          "per_job", 3],
    ["Assembly", "Apply lubricant to O-ring seats",                "per_job", 4],
    ["Assembly", "Torque sub-assembly connections to spec",        "per_job", 5],
    // Testing & QC
    ["Testing & QC", "Calibrate pressure test equipment",          "daily",   1],
    ["Testing & QC", "Perform hydraulic test to rated WP",         "per_job", 2],
    ["Testing & QC", "Inspect exterior finish and markings",       "per_job", 3],
    ["Testing & QC", "Complete ITP sign-off documentation",        "per_job", 4],
    ["Testing & QC", "Verify certificate of compliance vs WO",     "per_job", 5],
    // Shipping
    ["Shipping", "Update shipping manifest in system",             "daily",   1],
    ["Shipping", "Verify work order packing list completeness",    "per_job", 2],
    ["Shipping", "Apply export markings and origin labels",        "per_job", 3],
    ["Shipping", "Photograph finished product before boxing",      "per_job", 4],
    ["Shipping", "Check inert gas purge on pressure containers",   "per_job", 5],
  ];

  tasks.forEach((t, i) => {
    const comma = i < tasks.length - 1 ? "," : ";";
    console.log(
      `  ((SELECT id FROM sections WHERE name = '${t[0]}'), '${t[1]}', '${t[2]}', ${t[3]})${comma}`
    );
  });
}

main().catch(console.error);
